### ISSUE TITLE
Documentación sobre la minería de datos

### ISSUE THREAD

**Issue by psnti** [psnti/TFG-Pablo-Santidrian-Tudanca#17]

**Comment by alvarag** [comment]
Comentarios sobre la memoria.

[memoriaAAG.pdf](https://github.com/psnti/TFG-Pablo-Santidrian-Tudanca/files/4344726/memoriaAAG.pdf)


Recuerda que es preferible definir todas las issues al inicio del sprint, y no irlas creando sobre la marcha.
